"""empty message

Revision ID: 049bf5d579ec
Revises: 94d909990eac
Create Date: 2022-08-07 17:05:45.554059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049bf5d579ec'
down_revision = '94d909990eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('service', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping', 'service')
    # ### end Alembic commands ###
