"""empty message

Revision ID: 0df87be4fbab
Revises: f9d97f098cf6
Create Date: 2022-08-08 23:43:17.062886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0df87be4fbab'
down_revision = 'f9d97f098cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('addressfk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'people', 'address', ['addressfk'], ['id'])
    op.drop_column('people', 'postalcode')
    op.drop_column('people', 'state')
    op.drop_column('people', 'address')
    op.drop_column('people', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('city', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('people', sa.Column('address', mysql.VARCHAR(length=75), nullable=True))
    op.add_column('people', sa.Column('state', mysql.VARCHAR(length=2), server_default=sa.text("'OR'"), nullable=True))
    op.add_column('people', sa.Column('postalcode', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'addressfk')
    # ### end Alembic commands ###
