"""empty message

Revision ID: 1a7c93b8c040
Revises: 7830ccb494e2
Create Date: 2022-08-11 23:48:14.093236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7c93b8c040'
down_revision = '7830ccb494e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('is_employee', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'is_employee')
    # ### end Alembic commands ###
