"""empty message

Revision ID: 1d8bf79e6442
Revises: 8433d26185c3
Create Date: 2022-08-07 21:57:38.932351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d8bf79e6442'
down_revision = '8433d26185c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'employee')
    op.drop_column('people', 'customer')
    op.drop_constraint('project_ibfk_6', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'people', ['employeefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_ibfk_6', 'project', 'people', ['employeefk'], ['id'], ondelete='CASCADE')
    op.add_column('people', sa.Column('customer', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('people', sa.Column('employee', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
