"""empty message

Revision ID: 3a9d541d6f64
Revises: af5fbe6dd6a2
Create Date: 2022-09-12 13:02:12.432227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9d541d6f64'
down_revision = 'af5fbe6dd6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_lineitems', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_lineitems', 'date_created')
    # ### end Alembic commands ###
