"""empty message

Revision ID: 406424782de8
Revises: 7f7fcf1581e9
Create Date: 2022-07-30 21:32:09.556232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '406424782de8'
down_revision = '7f7fcf1581e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('project', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_column('people', 'active')
    # ### end Alembic commands ###
