"""empty message

Revision ID: 43720ad5c77f
Revises: 633664c407b0
Create Date: 2022-08-16 23:41:39.614964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43720ad5c77f'
down_revision = '633664c407b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('testimonials', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testimonials', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('printer', 'active')
    # ### end Alembic commands ###
