"""empty message

Revision ID: 4bfcd3bcdb52
Revises: bfcc5a09d3e5
Create Date: 2022-08-15 13:14:55.881481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfcd3bcdb52'
down_revision = 'bfcc5a09d3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('fulltext', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'fulltext')
    # ### end Alembic commands ###
