"""empty message

Revision ID: 50cfbb02640b
Revises: 53ac3aff8dc7
Create Date: 2022-07-28 01:25:29.103736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50cfbb02640b'
down_revision = '53ac3aff8dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('postalcode', sa.String(length=20), nullable=True))
    op.drop_column('user', 'zip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('user', 'postalcode')
    # ### end Alembic commands ###
