"""empty message

Revision ID: 51cca450bcb5
Revises: 91a90ff8b930
Create Date: 2022-08-09 00:14:44.952046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51cca450bcb5'
down_revision = '91a90ff8b930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_ibfk_1', 'address', type_='foreignkey')
    op.drop_column('address', 'peoplefk')
    op.add_column('people', sa.Column('main_addressfk', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('ship_addressfk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'people', 'address', ['main_addressfk'], ['id'])
    op.create_foreign_key(None, 'people', 'address', ['ship_addressfk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'ship_addressfk')
    op.drop_column('people', 'main_addressfk')
    op.add_column('address', sa.Column('peoplefk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('address_ibfk_1', 'address', 'people', ['peoplefk'], ['id'])
    # ### end Alembic commands ###
