"""empty message

Revision ID: 57f5e07fcb12
Revises: 87baf1bc1761
Create Date: 2022-07-29 02:31:05.968389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57f5e07fcb12'
down_revision = '87baf1bc1761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('kW_hr', sa.Float(), nullable=True))
    op.drop_column('printer', 'kW_hr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('kW_hr', mysql.FLOAT(), nullable=True))
    op.drop_column('filament', 'kW_hr')
    # ### end Alembic commands ###
