"""empty message

Revision ID: 59d54024f283
Revises: 76137da878d7
Create Date: 2022-07-28 02:00:51.241645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d54024f283'
down_revision = '76137da878d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'type')
    # ### end Alembic commands ###
