"""empty message

Revision ID: 5a5ca1603467
Revises: 59d54024f283
Create Date: 2022-07-28 02:01:29.874450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a5ca1603467'
down_revision = '59d54024f283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('densitygcm3', sa.Float(), nullable=True))
    op.drop_column('type', 'density_g_cm3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('density_g_cm3', mysql.FLOAT(), nullable=True))
    op.drop_column('type', 'densitygcm3')
    # ### end Alembic commands ###
