"""empty message

Revision ID: 5c7e3774b2ed
Revises: 43720ad5c77f
Create Date: 2022-08-17 18:21:07.383052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7e3774b2ed'
down_revision = '43720ad5c77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('current_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'current_quantity')
    op.drop_column('project', 'cost')
    op.drop_column('project', 'sale_price')
    # ### end Alembic commands ###
