"""empty message

Revision ID: 633664c407b0
Revises: 4bfcd3bcdb52
Create Date: 2022-08-15 13:28:32.353293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633664c407b0'
down_revision = '4bfcd3bcdb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('testimonials', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'date_created')
    op.drop_column('testimonials', 'active')
    # ### end Alembic commands ###
