"""empty message

Revision ID: 6c71669a04f1
Revises: ad89018e7717
Create Date: 2022-08-21 23:14:13.141252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c71669a04f1'
down_revision = 'ad89018e7717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('employeefk', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('customerfk', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('ordernum', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('date_time_created', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'sales', 'people', ['customerfk'], ['id'])
    op.create_foreign_key(None, 'sales', 'people', ['employeefk'], ['id'])
    op.add_column('sales_lineitems', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('sales_lineitems', sa.Column('ordernumfk', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_lineitems', 'ordernumfk')
    op.drop_column('sales_lineitems', 'price')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'date_time_created')
    op.drop_column('sales', 'ordernum')
    op.drop_column('sales', 'customerfk')
    op.drop_column('sales', 'employeefk')
    # ### end Alembic commands ###
