"""empty message

Revision ID: 76137da878d7
Revises: 3ea3831c9792
Create Date: 2022-07-28 01:53:06.274712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76137da878d7'
down_revision = '3ea3831c9792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('picture', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'picture')
    # ### end Alembic commands ###
