"""empty message

Revision ID: 7830ccb494e2
Revises: fd641ee86063
Create Date: 2022-08-11 21:50:59.699008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7830ccb494e2'
down_revision = 'fd641ee86063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('filament_ibfk_2', 'filament', type_='foreignkey')
    op.create_foreign_key(None, 'filament', 'people', ['supplierfk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.create_foreign_key('filament_ibfk_2', 'filament', 'people', ['supplierfk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
