"""empty message

Revision ID: 7f7fcf1581e9
Revises: a8208c28fa97
Create Date: 2022-07-29 13:11:48.444450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7fcf1581e9'
down_revision = 'a8208c28fa97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'active')
    # ### end Alembic commands ###
