"""empty message

Revision ID: 800e77a47e8d
Revises: c471be53490a
Create Date: 2022-08-22 13:19:21.237610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800e77a47e8d'
down_revision = 'c471be53490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sq_idempotency_key', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sq_idempotency_key')
    # ### end Alembic commands ###
