"""empty message

Revision ID: 836145506ffe
Revises: d596f696202c
Create Date: 2022-08-06 23:01:08.698351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '836145506ffe'
down_revision = 'd596f696202c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempdata')
    op.add_column('settings', sa.Column('padding_time', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('padding_filament', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'padding_filament')
    op.drop_column('settings', 'padding_time')
    op.create_table('tempdata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('textdata', mysql.TEXT(), nullable=True),
    sa.Column('numberdata', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('floatdata', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
