"""empty message

Revision ID: 8433d26185c3
Revises: e553cfacc1d9
Create Date: 2022-08-07 21:19:18.159382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8433d26185c3'
down_revision = 'e553cfacc1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employeefk', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'people', ['employeefk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('employeefk', 'project', 'people', ['employeefk'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
