"""empty message

Revision ID: 87baf1bc1761
Revises: 
Create Date: 2022-07-29 02:28:48.722423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87baf1bc1761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('kW_hr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'kW_hr')
    # ### end Alembic commands ###
