"""empty message

Revision ID: 88e61215e99b
Revises: 406424782de8
Create Date: 2022-07-30 21:32:57.746093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e61215e99b'
down_revision = '406424782de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'active')
    # ### end Alembic commands ###
