"""empty message

Revision ID: 8bb1f2b12eea
Revises: e88e72efdc08
Create Date: 2022-08-30 00:58:27.777192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb1f2b12eea'
down_revision = 'e88e72efdc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('correction_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'correction_percentage')
    # ### end Alembic commands ###
