"""empty message

Revision ID: 91a90ff8b930
Revises: 0df87be4fbab
Create Date: 2022-08-08 23:46:20.021238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91a90ff8b930'
down_revision = '0df87be4fbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('peoplefk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'people', ['peoplefk'], ['id'])
    op.drop_constraint('people_ibfk_1', 'people', type_='foreignkey')
    op.drop_column('people', 'addressfk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('addressfk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('people_ibfk_1', 'people', 'address', ['addressfk'], ['id'])
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'peoplefk')
    # ### end Alembic commands ###
