"""empty message

Revision ID: 93c0b620e1b7
Revises: e131587e5e61
Create Date: 2022-09-26 10:55:01.246577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c0b620e1b7'
down_revision = 'e131587e5e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('stars', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'stars')
    # ### end Alembic commands ###
