"""empty message

Revision ID: 94d909990eac
Revises: 836145506ffe
Create Date: 2022-08-07 16:55:47.087644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d909990eac'
down_revision = '836145506ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('tracking', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('ordernum', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'time_updated')
    op.drop_column('project', 'time_created')
    op.drop_column('project', 'ordernum')
    op.drop_column('project', 'tracking')
    # ### end Alembic commands ###
