"""empty message

Revision ID: a1f32666e00a
Revises: d455708b5efe
Create Date: 2022-08-09 00:27:42.387813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1f32666e00a'
down_revision = 'd455708b5efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('address', sa.Column('fname', sa.String(length=50), nullable=True))
    op.add_column('address', sa.Column('lname', sa.String(length=50), nullable=True))
    op.add_column('address', sa.Column('company', sa.String(length=50), nullable=True))
    op.add_column('address', sa.Column('address2', sa.String(length=75), nullable=True))
    op.drop_column('address', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('address', 'address2')
    op.drop_column('address', 'company')
    op.drop_column('address', 'lname')
    op.drop_column('address', 'fname')
    op.drop_column('address', 'type')
    # ### end Alembic commands ###
