"""empty message

Revision ID: a49b58e370bc
Revises: fdbdde1c8e7e
Create Date: 2022-11-03 18:07:46.195622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a49b58e370bc'
down_revision = 'fdbdde1c8e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event__inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event__inventory',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('eventid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('projectid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['eventid'], ['events.id'], name='event__inventory_ibfk_1'),
    sa.ForeignKeyConstraint(['projectid'], ['project.id'], name='event__inventory_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
