"""empty message

Revision ID: a8208c28fa97
Revises: 57f5e07fcb12
Create Date: 2022-07-29 02:48:44.922455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8208c28fa97'
down_revision = '57f5e07fcb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filament', 'kW_hr')
    op.add_column('type', sa.Column('kW_hr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'kW_hr')
    op.add_column('filament', sa.Column('kW_hr', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
