"""empty message

Revision ID: af5fbe6dd6a2
Revises: f478c697492e
Create Date: 2022-09-05 21:37:29.526850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5fbe6dd6a2'
down_revision = 'f478c697492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printobject', sa.Column('qtyperprint', sa.Integer(), nullable=True))
    op.add_column('printobject', sa.Column('projectid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'printobject', 'project', ['projectid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printobject', type_='foreignkey')
    op.drop_column('printobject', 'projectid')
    op.drop_column('printobject', 'qtyperprint')
    # ### end Alembic commands ###
