"""empty message

Revision ID: bfcc5a09d3e5
Revises: cb1c44e361b4
Create Date: 2022-08-15 00:50:09.219809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcc5a09d3e5'
down_revision = 'cb1c44e361b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('mapsurl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'mapsurl')
    # ### end Alembic commands ###
