"""empty message

Revision ID: c471be53490a
Revises: 6c71669a04f1
Create Date: 2022-08-21 23:53:48.737985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c471be53490a'
down_revision = '6c71669a04f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'total')
    # ### end Alembic commands ###
