"""empty message

Revision ID: cb1c44e361b4
Revises: e96c03d3a520
Create Date: 2022-08-14 00:35:49.972868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1c44e361b4'
down_revision = 'e96c03d3a520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('publish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'publish')
    # ### end Alembic commands ###
