"""empty message

Revision ID: d455708b5efe
Revises: 51cca450bcb5
Create Date: 2022-08-09 00:22:37.324941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd455708b5efe'
down_revision = '51cca450bcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('peoplefk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'people', ['peoplefk'], ['id'])
    op.drop_column('people', 'ship_lname')
    op.drop_column('people', 'ship_address')
    op.drop_column('people', 'ship_postalcode')
    op.drop_column('people', 'ship_state')
    op.drop_column('people', 'ship_city')
    op.drop_column('people', 'ship_fname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('ship_fname', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('people', sa.Column('ship_city', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('people', sa.Column('ship_state', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('people', sa.Column('ship_postalcode', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('people', sa.Column('ship_address', mysql.VARCHAR(length=75), nullable=True))
    op.add_column('people', sa.Column('ship_lname', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'peoplefk')
    # ### end Alembic commands ###
