"""empty message

Revision ID: d596f696202c
Revises: e3f56589daec
Create Date: 2022-08-03 01:12:17.428662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd596f696202c'
down_revision = 'e3f56589daec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('zipcode', sa.Integer(), nullable=True))
    op.add_column('states', sa.Column('city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'city')
    op.drop_column('states', 'zipcode')
    # ### end Alembic commands ###
