"""empty message

Revision ID: e131587e5e61
Revises: e53ef39014bf
Create Date: 2022-09-19 23:09:54.764359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e131587e5e61'
down_revision = 'e53ef39014bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'priority')
    # ### end Alembic commands ###
