"""empty message

Revision ID: e3f56589daec
Revises: 88e61215e99b
Create Date: 2022-07-30 23:40:16.243543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f56589daec'
down_revision = '88e61215e99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'email')
    # ### end Alembic commands ###
