"""empty message

Revision ID: e53ef39014bf
Revises: 3a9d541d6f64
Create Date: 2022-09-19 16:55:14.411176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53ef39014bf'
down_revision = '3a9d541d6f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('bizstarttime', sa.Time(), nullable=True))
    op.add_column('settings', sa.Column('bizendtime', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'bizendtime')
    op.drop_column('settings', 'bizstarttime')
    # ### end Alembic commands ###
