"""empty message

Revision ID: e553cfacc1d9
Revises: 049bf5d579ec
Create Date: 2022-08-07 21:16:27.057893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e553cfacc1d9'
down_revision = '049bf5d579ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('employeefk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project', 'people', ['employeefk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'employeefk')
    # ### end Alembic commands ###
