"""empty message

Revision ID: e88e72efdc08
Revises: 800e77a47e8d
Create Date: 2022-08-24 23:52:32.144377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88e72efdc08'
down_revision = '800e77a47e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'threshold')
    # ### end Alembic commands ###
