"""empty message

Revision ID: f3d9afbe4a0d
Revises: 1d8bf79e6442
Create Date: 2022-08-07 22:07:24.666024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d9afbe4a0d'
down_revision = '1d8bf79e6442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('ship_fname', sa.String(length=50), nullable=True))
    op.add_column('people', sa.Column('ship_lname', sa.String(length=50), nullable=True))
    op.add_column('people', sa.Column('ship_address', sa.String(length=75), nullable=True))
    op.add_column('people', sa.Column('ship_city', sa.String(length=50), nullable=True))
    op.add_column('people', sa.Column('ship_state', sa.String(length=2), nullable=True))
    op.add_column('people', sa.Column('ship_postalcode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'ship_postalcode')
    op.drop_column('people', 'ship_state')
    op.drop_column('people', 'ship_city')
    op.drop_column('people', 'ship_address')
    op.drop_column('people', 'ship_lname')
    op.drop_column('people', 'ship_fname')
    # ### end Alembic commands ###
