"""empty message

Revision ID: f478c697492e
Revises: 8bb1f2b12eea
Create Date: 2022-08-30 11:39:35.144110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f478c697492e'
down_revision = '8bb1f2b12eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'objectfk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('project_ibfk_7', 'project', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('project_ibfk_7', 'project', 'printobject', ['objectfk'], ['id'], ondelete='CASCADE')
    op.alter_column('project', 'objectfk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
