"""empty message

Revision ID: fd641ee86063
Revises: 456ec2935182
Create Date: 2022-08-11 21:44:28.438414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd641ee86063'
down_revision = '456ec2935182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('supplierfk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'filament', 'people', ['supplierfk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_column('filament', 'supplierfk')
    # ### end Alembic commands ###
